# Generated by Django 5.2.5 on 2025-12-11 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Момент перемещения файла в корзину.', null=True),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Флаг soft-delete: файл перемещён в корзину.'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['is_deleted', 'deleted_at'], name='storageapp__is_dele_a42913_idx'),
        ),
    ]
