# Generated by Django 5.2.5 on 2025-12-12 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0002_storedfile_deleted_at_storedfile_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='is_folder',
            field=models.BooleanField(db_index=True, default=False, help_text='Является ли объект папкой'),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Родительская папка (null = корень)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storageapp.storedfile'),
        ),
    ]
