# Generated by Django 5.2.5 on 2025-12-17 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0003_storedfile_is_folder_storedfile_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='deleted_from',
            field=models.ForeignKey(blank=True, help_text='Папка, из которой объект был отправлен в корзину (для отображения исходного места).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_children', to='storageapp.storedfile'),
        ),
    ]
