# Generated by Django 5.2.5 on 2025-12-17 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0004_storedfile_deleted_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='deleted_from',
            field=models.ForeignKey(blank=True, help_text='Папка, из которой объект был отправлен в корзину (для отображения исходного места).', limit_choices_to={'is_folder': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_children', to='storageapp.storedfile'),
        ),
    ]
