name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  compose-build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Compose version
        run: docker compose version

      - name: Build images
        working-directory: deploy
        run: |
          docker compose build --pull --no-cache

      - name: Start DB
        working-directory: deploy
        run: |
          docker compose up -d db
          # wait for Postgres
          for i in {1..30}; do
            docker compose exec -T db pg_isready -U ${POSTGRES_USER:-postgres} && break
            sleep 2
          done

      - name: Prepare volumes (optional)
        working-directory: deploy
        run: |
          docker compose run --rm \
            -e DJANGO_SETTINGS_MODULE=mycloud.settings.prod \
            -e DATABASE_URL="postgres://postgres:postgres@db:5432/mycloud" \
            backend bash -lc 'mkdir -p static_front media && echo "ok"'

      - name: Make migrations (accounts, storageapp)
        working-directory: deploy
        run: |
          docker compose run --rm \
            -e DJANGO_SETTINGS_MODULE=mycloud.settings.prod \
            -e DATABASE_URL="postgres://postgres:postgres@db:5432/mycloud" \
            backend bash -lc 'python manage.py makemigrations accounts storageapp --noinput || true'

      - name: Django check (sanity)
        working-directory: deploy
        run: |
          docker compose run --rm \
            -e DJANGO_SETTINGS_MODULE=mycloud.settings.prod \
            -e DATABASE_URL="postgres://postgres:postgres@db:5432/mycloud" \
            backend python manage.py check

      - name: Show migrations (debug)
        working-directory: deploy
        run: |
          docker compose run --rm \
            -e DJANGO_SETTINGS_MODULE=mycloud.settings.prod \
            -e DATABASE_URL="postgres://postgres:postgres@db:5432/mycloud" \
            backend python manage.py showmigrations accounts

      - name: Run migrations
        working-directory: deploy
        run: |
          docker compose run --rm \
            -e DJANGO_SETTINGS_MODULE=mycloud.settings.prod \
            -e DATABASE_URL="postgres://postgres:postgres@db:5432/mycloud" \
            backend python manage.py migrate --noinput

      - name: Run backend tests (storageapp only)
        working-directory: deploy
        run: |
          docker compose run --rm \
            -e DJANGO_SETTINGS_MODULE=mycloud.settings.prod \
            -e DATABASE_URL="postgres://postgres:postgres@db:5432/mycloud" \
            backend bash -lc 'python manage.py test storageapp -v 2 --noinput'

      - name: Compose down
        if: always()
        working-directory: deploy
        run: docker compose down -v
